spring:
  application:
    name: ticketing
  datasource:
    url: jdbc:mysql://localhost:3307/ticketing
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    show-sql: true
  web:
    locale: en
    locale-resolver: fixed