spring:
  application:
    name: ticketing
  datasource:
    url: jdbc:h2:mem:ticketing
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    show-sql: true
  web:
    locale: en
    locale-resolver: fixed